# syntax=docker/dockerfile:1.1.7-experimental
############################
# Pynv but no environments #
############################
# NOTE: If you change the image version change it also in create_builds.py
ARG IMAGE_VERSION=3.20
FROM alpine:$IMAGE_VERSION as pyenv_clean
ENV CFLAGS='-O2'

RUN apk add --no-cache \
        cargo \
        curl \
        git \
        bash \
        openssh-client \
        # PyEnv deps
        bzip2-dev coreutils dpkg-dev dpkg expat-dev patch \
        findutils gcc gdbm-dev libc-dev libffi-dev libnsl-dev libtirpc-dev \
        linux-headers make ncurses-dev openssl-dev pax-utils readline-dev \
        sqlite-dev tcl-dev tk tk-dev util-linux-dev xz-dev zlib-dev \
    # githublab ssh
    && mkdir -p -m 0700 ~/.ssh && ssh-keyscan gitlab.com github.com | sort > ~/.ssh/known_hosts \
    # install pyenv
    && curl -o /tmp/pyenv_setup.sh --keepalive-time 900 --proto '=https' --tlsv1.2 -vsSfL https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer \
    && chmod +x /tmp/pyenv_setup.sh \
    && /tmp/pyenv_setup.sh \
    && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile \
    && echo 'export PATH="$PYENV_ROOT/bin:$HOME/.cargo/bin:$PATH"' >> ~/.profile \
    && echo 'eval "$(pyenv init --path)"' >> ~/.profile \
    && true

SHELL ["/bin/bash", "-lc"]
ENTRYPOINT ["/bin/bash", "-lc"]

RUN pyenv install -l

##############################
# Build the version resolver #
##############################
FROM pyenv_clean as pyenv_resolve_build
COPY pyenv_resolve /build
RUN cd /build \
    && cargo build --release \
    && cargo install --path . \
    && true

###########################
# Prebuild given versions #
###########################
FROM pyenv_clean as pyenv_prebuild
COPY --from=pyenv_resolve_build /root/.cargo /root/.cargo
ARG BUILD_PYTHON_VERSIONS="3.11 3.12 3.13 3.10 3.9"
RUN export RESOLVED_VERSIONS=`pyenv_resolve $BUILD_PYTHON_VERSIONS` \
    && echo RESOLVED_VERSIONS=$RESOLVED_VERSIONS \
    && for pyver in $RESOLVED_VERSIONS; do pyenv install $pyver; done \
    && pyenv global $RESOLVED_VERSIONS

####################################
# Pyenv shell with default version #
####################################
FROM pyenv_prebuild as pyenv
CMD ["python"]

###############################
# tox and poetry preinstalled #
###############################
FROM pyenv as tox-base
COPY docker-entrypoint-tox.sh /
RUN python -m pip install -U tox \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.profile \
    && true
ONBUILD COPY . /app
WORKDIR /app
ENTRYPOINT ["/docker-entrypoint-tox.sh"]
