# syntax=docker/dockerfile:1.1.7-experimental
############################
# Pynv but no environments #
############################
ARG IMAGE_VERSION=buster
FROM debian:$IMAGE_VERSION-slim as pyenv_clean
ENV CFLAGS='-O2' \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       bash \
       curl \
       ca-certificates \
       git-core \
       make \
       llvm \
       build-essential \
       openssh-client \
       libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget \
       libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
    # githublab ssh
    && mkdir -p -m 0700 ~/.ssh && ssh-keyscan gitlab.com github.com | sort > ~/.ssh/known_hosts \
    # install pyenv
    && curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash \
    && echo 'export PATH="/root/.pyenv/bin:$PATH"' >> /root/.profile \
    && echo 'eval "$(pyenv init -)"' >> /root/.profile \
    && true

SHELL ["/bin/bash", "-lc"]
ENTRYPOINT ["/bin/bash", "-lc"]


###########################
# Prebuild given versions #
###########################
FROM pyenv_clean as pyenv_prebuild
ARG BUILD_PYTHON_VERSIONS="3.9.0 3.8.6 3.7.9 3.6.12"

RUN for pyver in $BUILD_PYTHON_VERSIONS; do pyenv install $pyver; done \
    && pyenv global $BUILD_PYTHON_VERSIONS

####################################
# Pyenv shell with default version #
####################################
FROM pyenv_prebuild as pyenv
CMD ["python"]

###############################
# tox and poetry preinstalled #
###############################
FROM pyenv as tox-base
COPY docker-entrypoint-tox.sh /
RUN python -m pip install -U tox \
    && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 \
    && true
ONBUILD COPY . /app
WORKDIR /app
ENTRYPOINT ["/docker-entrypoint-tox.sh"]
