[tool.poetry]
name = "toxtest"
version = "0.1.0"
description = "Tox needs a python project"
authors = ["Eero af Heurlin <eero.afheurlin@advian.fi>", "Joni Kähärä <joni.kahara@advian.fi>"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.dependencies]
python = "^3.6"
msgpack = "^1.0"
dataclasses = { version = "^0.7", python = "~3.6" }

[tool.poetry.dev-dependencies]
pytest = "^3.0"
coverage = {version = "^4.5", extras = ["toml"]}
pytest-cov = "^2.8"
pylint = "^2.4"
black = "=19.10.b0"
