on:
  push:
    branches:
      - 'master'
  workflow_dispatch:  # Allow manual triggering

jobs:
  bake_pyenv:
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        timeout-minutes: 20
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true  # we want to re-download freshest layers anyway
          swap-storage: true
      -
        name: Checkout
        timeout-minutes: 20
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        timeout-minutes: 60
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        timeout-minutes: 20
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: ./buildkitd.toml
      -
        name: Login to DockerHub
        timeout-minutes: 5
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        timeout-minutes: 5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create bakefiles
        timeout-minutes: 5
        run: |
          export DHUBREPO=advian
          ./create_builds.py pyenv > pyenv.hcl

      - name: Bake pyenv
        timeout-minutes: 1440
        run: |
          docker buildx bake --pull --provenance=true --sbom=true --push --file ./pyenv.hcl
# FIXME: How to copy the buildx cache between jobs ?
  bake_tox:
    runs-on: ubuntu-latest
    needs: bake_pyenv
    steps:
      - name: Free Disk Space (Ubuntu)
        timeout-minutes: 20
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true  # we want to re-download freshest layers anyway
          swap-storage: true
      -
        name: Checkout
        timeout-minutes: 20
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        timeout-minutes: 60
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        timeout-minutes: 20
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: ./buildkitd.toml
      -
        name: Login to DockerHub
        timeout-minutes: 5
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        timeout-minutes: 5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create bakefiles
        timeout-minutes: 5
        run: |
          export DHUBREPO=advian
          ./create_builds.py tox-base > tox-base.hcl
      - name: Bake pyenv
        timeout-minutes: 1440
        run: |
          docker buildx bake --pull --provenance=true --sbom=true --push --file ./tox-base.hcl
