on:
  push:
    branches:
      - 'master'
  workflow_dispatch:  # Allow manual triggering

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Create bakefiles
        run: |
          export DHUBREPO=advian
          ./create_builds.py pyenv > pyenv.hcl
          ./create_builds.py tox-base > tox-base.hcl

      - name: Bake pyenv
        run: |
          docker buildx bake --push --file ./pyenv.hcl

      - name: Bake tox
        run: |
          docker buildx bake --push --file ./tox-base.hcl
